#!/bin/bash
set -e

printf "\n\e[0;32m🍣   Removing build folder...\e[0m\n\n"

rm -rf build
mkdir build
mkdir build/TEMP

printf "\n\e[0;32m🍣   Copying folders...\e[0m\n\n"

# cp docs/favicon.ico build/favicon.ico
# cp docs/_redirects build/_redirects

cp -r docs/images build/

printf "\n\e[0;32m🍣   Copying files...\e[0m\n\n"

cp docs/index.html  build/TEMP/temp.html
node_modules/.bin/replace '(<script class="dev-only".*</script>)' '<!-- $1 -->' build/TEMP/temp.html -m -i --silent
node_modules/.bin/replace '<!-- prod-only (.*) -->' '$1' build/TEMP/temp.html -m -i --silent
node_modules/.bin/html-minifier -o build/index.html build/TEMP/temp.html --remove-comments --collapse-whitespace --minify-css --minify-js --preserve-line-breaks
node_modules/.bin/replace '^(?:[\t ]*(?:\r?\n|\r))+' '' build/index.html -m -i

cp docs/simple.html  build/TEMP/temp.html
node_modules/.bin/replace '(<script class="dev-only".*</script>)' '<!-- $1 -->' build/TEMP/temp.html -m -i --silent
node_modules/.bin/replace '<!-- prod-only (.*) -->' '$1' build/TEMP/temp.html -m -i --silent
node_modules/.bin/html-minifier -o build/simple.html build/TEMP/temp.html --remove-comments --collapse-whitespace --minify-css --minify-js --preserve-line-breaks
node_modules/.bin/replace '^(?:[\t ]*(?:\r?\n|\r))+' '' build/simple.html -m -i

node_modules/.bin/elm make --output=build/TEMP/temp.js src/Main.elm --optimize
node_modules/.bin/uglifyjs build/TEMP/temp.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | node_modules/.bin/uglifyjs --mangle --output=build/elm-masonry.js

node_modules/.bin/elm make --output=build/TEMP/temp.js src/Simple.elm --optimize
node_modules/.bin/uglifyjs build/TEMP/temp.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | node_modules/.bin/uglifyjs --mangle --output=build/elm-masonry-simple.js

printf "\n\e[0;32m🍣   Cleaning up...\e[0m\n\n"

rm -rf build/TEMP
