#!/bin/bash
set -e

node_modules/.bin/elm-go src/Simple.elm --ide=atom --dir=docs --start-page=simple.html --path-to-elm=node_modules/.bin/elm --port=8001 -- --output=docs/elm-masonry-simple.js --debug
